export { default as About } from "./about";
export { default as Contact } from "./contact";
export { default as Footer } from "./footer";
export { default as Gallery } from "./gallery";
export { default as Hero } from "./hero";
export { default as History } from "./history";
export { default as Navbar } from "./navbar"
export { default as Logo } from "./logo";
export { default as Services } from "./services";
